### ISSUE TITLE
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory

### ISSUE THREAD

**Issue by Owned67** [serversideup/docker-proftpd#1]
> sudo docker pull serversideup/proftpd
 Using default tag: latest
 latest: Pulling from serversideup/proftpd
 d1fbec07a2e5: Pull complete
 a638c4f512ae: Pull complete
 a66d9ee1287b: Pull complete
 4e649c9a74df: Pull complete
 9530cf5d3df1: Pull complete
 61ebffb03538: Pull complete
 312a9941c200: Pull complete
 Digest: sha256:1de55acd6c7eae9fe39af6e9acbcf96c71c3674ed18bc22cd3ea095dcb70b786
 Status: Downloaded newer image for serversideup/proftpd:latest
 docker.io/serversideup/proftpd:latest
 Owned67@debian:~$ sudo docker build -t proftpd-mysql .
 [+] Building 0.2s (1/1) FINISHED                                                                                                                              docker:default
  => [internal] load build definition from Dockerfile                                                                                                                    0.1s
  => => transferring dockerfile: 2B                                                                                                                                      0.0s
 ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory

**Comment by jaydrogers** [comment]
This is a build issue not related to the images.

You're running the `sudo docker build -t proftpd-mysql .` command in your home directory where a file called `Dockerfile` does not exist.
